spring.application.name=Livraria
server.port=8081
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


spring.datasource.url=jdbc:mysql://localhost:3306/livraria?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Vevet0pnice@11
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true